org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

mod_id=narutofix
mod_name=NarutoFix
mod_group_id=com.qdd.narutofix
mod_version=0.2.9
mod_authors=qdd
mod_description=Fix NarutoMod.

minecraft_version=1.12.2
mcp_mapping_channel=stable
mcp_mapping_version=39

use_mixins=true
mixin_configs=narutofix,narutofix_early
mixin_refmap=refmap.narutofix.json
mixin_package=com.qdd.narutofix.mixin
mixinbooter_version=10.7
mixinextras_version=0.5.0

use_coremod=true
is_coremod=true
coremod_plugin_class_name=com.qdd.narutofix.core.FixPlugin

use_access_transformer=true
access_transformer_locations=narutofix_at.cfg

use_asset_mover=true
asset_mover_version=2.0

extra_jvm_args=-Dfml.coreMods.load=com.qdd.narutofix.core.FixPlugin

repoHost=http://192.168.30.100:30002
repoUser=qdd
repoToken=DHUqcz123@
